# Generated by Django 4.1.7 on 2023-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='Visp, Switzerland', max_length=100),
            preserve_default=False,
        ),
    ]
